// GENERATED FILE. Do not edit by hand.
class UobBuilding {
  final String name;
  final double latitude;
  final double longitude;
  final List<String> aliases;
  const UobBuilding({
    required this.name,
    required this.latitude,
    required this.longitude,
    required this.aliases,
  });
}

const List<UobBuilding> uobBuildings = [
  UobBuilding(
    name: '1 South',
    latitude: 51.37791,
    longitude: -2.33031,
    aliases: ['1 South', '1 south', '1S', '1s'],
  ),
  UobBuilding(
    name: '1 West',
    latitude: 51.379924,
    longitude: -2.328749,
    aliases: ['1 West', '1 west', '1W', '1w'],
  ),
  UobBuilding(
    name: '1 West North',
    latitude: 51.38046,
    longitude: -2.32856,
    aliases: ['1 West North', '1 west north', '1WN', '1wn'],
  ),
  UobBuilding(
    name: '10 East',
    latitude: 51.37823851155287,
    longitude: -2.3255707200942273,
    aliases: ['10 East', '10 east', '10E', '10e'],
  ),
  UobBuilding(
    name: '10 West',
    latitude: 51.3795,
    longitude: -2.33193,
    aliases: ['10 West', '10 west', '10W', '10w'],
  ),
  UobBuilding(
    name: '10 West Graduate Commons',
    latitude: 51.3795,
    longitude: -2.33193,
    aliases: ['10 West Graduate Commons', '10 west graduate commons'],
  ),
  UobBuilding(
    name: '2 East',
    latitude: 51.37924,
    longitude: -2.32775,
    aliases: ['2 East', '2 east', '2E', '2e'],
  ),
  UobBuilding(
    name: '3 East',
    latitude: 51.38023,
    longitude: -2.32725,
    aliases: ['3 East', '3 east', '3E', '3e'],
  ),
  UobBuilding(
    name: '3 West',
    latitude: 51.38003,
    longitude: -2.329391,
    aliases: ['3 West', '3 west', '3W', '3w'],
  ),
  UobBuilding(
    name: '3 West North',
    latitude: 51.38054,
    longitude: -2.32928,
    aliases: ['3 West North', '3 west north', '3WN', '3wn'],
  ),
  UobBuilding(
    name: '4 East South',
    latitude: 51.37849,
    longitude: -2.32719,
    aliases: ['4 East South', '4 east south', '4ES', '4es'],
  ),
  UobBuilding(
    name: '4 South',
    latitude: 51.37748,
    longitude: -2.32931,
    aliases: ['4 South', '4 south', '4S', '4s'],
  ),
  UobBuilding(
    name: '4 West',
    latitude: 51.37957,
    longitude: -2.32931,
    aliases: ['4 West', '4 west', '4W', '4w'],
  ),
  UobBuilding(
    name: '4W Cafe',
    latitude: 51.37967,
    longitude: -2.32954,
    aliases: ['4W Cafe', '4w cafe', '4w cafe'],
  ),
  UobBuilding(
    name: '5 West',
    latitude: 51.38011,
    longitude: -2.331003,
    aliases: ['5 West', '5 west', '5W', '5w'],
  ),
  UobBuilding(
    name: '6 East',
    latitude: 51.3791,
    longitude: -2.32593,
    aliases: ['6 East', '6 east', '6E', '6e'],
  ),
  UobBuilding(
    name: '6 West',
    latitude: 51.379241,
    longitude: -2.329845,
    aliases: ['6 West', '6 west', '6W', '6w'],
  ),
  UobBuilding(
    name: '6 West South',
    latitude: 51.37897,
    longitude: -2.32988,
    aliases: ['6 West South', '6 west south', '6WS', '6ws'],
  ),
  UobBuilding(
    name: '8 West',
    latitude: 51.37974,
    longitude: -2.33105,
    aliases: ['8 West', '8 west', '8W', '8w'],
  ),
  UobBuilding(
    name: '9 West',
    latitude: 51.38026,
    longitude: -2.3314,
    aliases: ['9 West', '9 west', '9W', '9w'],
  ),
  UobBuilding(
    name: 'Amazon Locker',
    latitude: 51.38005,
    longitude: -2.3297,
    aliases: ['Amazon Locker', 'amazon locker'],
  ),
  UobBuilding(
    name: 'Assistive Technology Room',
    latitude: 51.38,
    longitude: -2.32811,
    aliases: ['Assistive Technology Room', 'assistive technology room'],
  ),
  UobBuilding(
    name: 'Brendon Court accommodation block',
    latitude: 51.38085,
    longitude: -2.32811,
    aliases: [
      'Brendon Court accommodation block',
      'brendon court accommodation block',
    ],
  ),
  UobBuilding(
    name: 'Campus bus terminus',
    latitude: 51.37907,
    longitude: -2.32538,
    aliases: ['Campus bus terminus', 'campus bus terminus'],
  ),
  UobBuilding(
    name: 'Campus Infrastructure Building',
    latitude: 51.38044,
    longitude: -2.32602,
    aliases: [
      'Campus Infrastructure Building',
      'campus infrastructure building',
    ],
  ),
  UobBuilding(
    name: 'Central Stores',
    latitude: 51.37643,
    longitude: -2.32587,
    aliases: ['Central Stores', 'central stores'],
  ),
  UobBuilding(
    name: 'Centre for Learning & Teaching (CLT)',
    latitude: 51.37997,
    longitude: -2.329863,
    aliases: [
      'Centre for Learning & Teaching (CLT)',
      'centre for learning   teaching  clt',
      'centre for learning & teaching (clt)',
      'centre for learning teaching clt',
    ],
  ),
  UobBuilding(
    name: 'Chaplaincy Centre',
    latitude: 51.37998,
    longitude: -2.32753,
    aliases: ['Chaplaincy Centre', 'chaplaincy centre'],
  ),
  UobBuilding(
    name: 'Claverton Rooms',
    latitude: 51.37953,
    longitude: -2.32832,
    aliases: ['Claverton Rooms', 'claverton rooms'],
  ),
  UobBuilding(
    name: 'Community Garden',
    latitude: 51.379313,
    longitude: -2.334538,
    aliases: ['Community Garden', 'community garden'],
  ),
  UobBuilding(
    name: 'David Bullett Nanofabrication Facility',
    latitude: 51.38022,
    longitude: -2.32899,
    aliases: [
      'David Bullett Nanofabrication Facility',
      'david bullett nanofabrication facility',
    ],
  ),
  UobBuilding(
    name: 'Department of Marketing, Communications, and External Affairs',
    latitude: 51.379748,
    longitude: -2.329987,
    aliases: [
      'Department of Marketing, Communications, and External Affairs',
      'department of marketing  communications  and external affairs',
      'department of marketing communications and external affairs',
      'department of marketing, communications, and external affairs',
    ],
  ),
  UobBuilding(
    name: 'Departmental Mail Services',
    latitude: 51.38088,
    longitude: -2.32578,
    aliases: ['Departmental Mail Services', 'departmental mail services'],
  ),
  UobBuilding(
    name: 'Doctoral College',
    latitude: 51.3795,
    longitude: -2.33193,
    aliases: ['Doctoral College', 'doctoral college'],
  ),
  UobBuilding(
    name: 'DReaM Facility',
    latitude: 51.380167,
    longitude: -2.331446,
    aliases: ['DReaM Facility', 'dream facility'],
  ),
  UobBuilding(
    name: 'East Accommodation Centre',
    latitude: 51.380282,
    longitude: -2.322819,
    aliases: ['East Accommodation Centre', 'east accommodation centre'],
  ),
  UobBuilding(
    name: 'East Building',
    latitude: 51.37887,
    longitude: -2.32301,
    aliases: [
      'EB',
      'East Bldg',
      'East Bldg.',
      'East Building',
      'eb',
      'east bldg',
      'east bldg.',
      'east building',
    ],
  ),
  UobBuilding(
    name: 'East Car Park',
    latitude: 51.37549,
    longitude: -2.323,
    aliases: ['East Car Park', 'east car park'],
  ),
  UobBuilding(
    name: 'East Car Park Overflow',
    latitude: 51.37699,
    longitude: -2.32069,
    aliases: ['East Car Park Overflow', 'east car park overflow'],
  ),
  UobBuilding(
    name: 'Eastwood accommodation complex',
    latitude: 51.38136,
    longitude: -2.32382,
    aliases: [
      'Eastwood accommodation complex',
      'eastwood accommodation complex',
    ],
  ),
  UobBuilding(
    name: 'Eastwood Lodge parcel room',
    latitude: 51.380713,
    longitude: -2.325811,
    aliases: ['Eastwood Lodge parcel room', 'eastwood lodge parcel room'],
  ),
  UobBuilding(
    name: 'Esther Parkin Residence',
    latitude: 51.3809159,
    longitude: -2.327165,
    aliases: ['Esther Parkin Residence', 'esther parkin residence'],
  ),
  UobBuilding(
    name: 'Founders Hall',
    latitude: 51.37968,
    longitude: -2.32623,
    aliases: ['Founders Hall', 'founders hall'],
  ),
  UobBuilding(
    name: 'Fountain Canteen',
    latitude: 51.37946,
    longitude: -2.32839,
    aliases: ['Fountain Canteen', 'fountain canteen'],
  ),
  UobBuilding(
    name: 'Fresh',
    latitude: 51.38,
    longitude: -2.32974,
    aliases: ['Fresh', 'fresh'],
  ),
  UobBuilding(
    name: 'Interpreting laboratories',
    latitude: 51.37993066709678,
    longitude: -2.3283183574676514,
    aliases: ['Interpreting laboratories', 'interpreting laboratories'],
  ),
  UobBuilding(
    name: 'IT Purchasing',
    latitude: 51.37979,
    longitude: -2.32832,
    aliases: ['IT Purchasing', 'it purchasing'],
  ),
  UobBuilding(
    name: 'IT Service Desk',
    latitude: 51.3799729,
    longitude: -2.3278847,
    aliases: ['IT Service Desk', 'it service desk'],
  ),
  UobBuilding(
    name: 'Lime Tree',
    latitude: 51.3794172,
    longitude: -2.3258355,
    aliases: ['Lime Tree', 'lime tree'],
  ),
  UobBuilding(
    name: 'Marlborough Court and Solsbury Court accommodation complex',
    latitude: 51.38046,
    longitude: -2.3242,
    aliases: [
      'Marlborough Court and Solsbury Court accommodation complex',
      'marlborough court and solsbury court accommodation complex',
    ],
  ),
  UobBuilding(
    name: 'Milner Centre for Evolution',
    latitude: 51.3773,
    longitude: -2.32848,
    aliases: ['Milner Centre for Evolution', 'milner centre for evolution'],
  ),
  UobBuilding(
    name: 'Muslim prayer room',
    latitude: 51.37944,
    longitude: -2.32714,
    aliases: ['Muslim prayer room', 'muslim prayer room'],
  ),
  UobBuilding(
    name: 'North Car Park',
    latitude: 51.38128,
    longitude: -2.3286,
    aliases: ['North Car Park', 'north car park'],
  ),
  UobBuilding(
    name: 'Norwood House accommodation block',
    latitude: 51.37928,
    longitude: -2.32716,
    aliases: [
      'Norwood House accommodation block',
      'norwood house accommodation block',
    ],
  ),
  UobBuilding(
    name: 'Norwood House Study Space',
    latitude: 51.37966,
    longitude: -2.32708,
    aliases: ['Norwood House Study Space', 'norwood house study space'],
  ),
  UobBuilding(
    name: 'Osborne House accommodation block',
    latitude: 51.3763554,
    longitude: -2.3314334,
    aliases: [
      'Osborne House accommodation block',
      'osborne house accommodation block',
    ],
  ),
  UobBuilding(
    name: 'Parade',
    latitude: 51.3794524,
    longitude: -2.3283018,
    aliases: ['Parade', 'parade'],
  ),
  UobBuilding(
    name: 'Polden accommodation block',
    latitude: 51.38066,
    longitude: -2.33176,
    aliases: ['Polden accommodation block', 'polden accommodation block'],
  ),
  UobBuilding(
    name: 'Polden Court accommodation block',
    latitude: 51.38078,
    longitude: -2.33186,
    aliases: [
      'Polden Court accommodation block',
      'polden court accommodation block',
    ],
  ),
  UobBuilding(
    name: 'Post Office',
    latitude: 51.38,
    longitude: -2.32974,
    aliases: ['Post Office', 'post office'],
  ),
  UobBuilding(
    name: 'Print Services and Photography Studio',
    latitude: 51.37979,
    longitude: -2.33058,
    aliases: [
      'Print Services and Photography Studio',
      'print services and photography studio',
    ],
  ),
  UobBuilding(
    name: 'South Car Park',
    latitude: 51.3769,
    longitude: -2.32722,
    aliases: ['South Car Park', 'south car park'],
  ),
  UobBuilding(
    name: 'Sports Cafe',
    latitude: 51.3776,
    longitude: -2.32335,
    aliases: ['Sports Cafe', 'sports cafe', 'sports cafe'],
  ),
  UobBuilding(
    name: 'Sports Training Village (STV)',
    latitude: 51.37758,
    longitude: -2.32468,
    aliases: [
      'Sports Training Village (STV)',
      'sports training village  stv',
      'sports training village (stv)',
      'sports training village stv',
    ],
  ),
  UobBuilding(
    name: 'Student Finance Office',
    latitude: 51.3796,
    longitude: -2.33,
    aliases: ['Student Finance Office', 'student finance office'],
  ),
  UobBuilding(
    name: 'Students\' Union',
    latitude: 51.3797,
    longitude: -2.32686,
    aliases: [
      'Students\' Union',
      'students  union',
      'students union',
      'students\' union',
    ],
  ),
  UobBuilding(
    name: 'The Chancellors\' Building',
    latitude: 51.3801,
    longitude: -2.32586,
    aliases: [
      'CB',
      'Chancellors Building',
      'Chancellors\' Building',
      'Chancellor\'s Building',
      'The Chancellors\' Building',
      'cb',
      'chancellors building',
      'chancellors\' building',
      'chancellor\'s building',
      'the chancellors  building',
      'the chancellors building',
      'the chancellors\' building',
    ],
  ),
  UobBuilding(
    name: 'The Edge',
    latitude: 51.37858,
    longitude: -2.32445,
    aliases: ['Edge', 'The Edge', 'edge', 'the edge'],
  ),
  UobBuilding(
    name: 'The Hut',
    latitude: 51.37998,
    longitude: -2.32538,
    aliases: ['Hut', 'The Hut', 'hut', 'the hut'],
  ),
  UobBuilding(
    name: 'The Library',
    latitude: 51.3799729,
    longitude: -2.3278847,
    aliases: ['Library', 'The Library', 'library', 'the library'],
  ),
  UobBuilding(
    name: 'The Market',
    latitude: 51.37971,
    longitude: -2.32677,
    aliases: ['Market', 'The Market', 'market', 'the market'],
  ),
  UobBuilding(
    name: 'The Pitstop',
    latitude: 51.37962,
    longitude: -2.32698,
    aliases: ['Pitstop', 'The Pitstop', 'pitstop', 'the pitstop'],
  ),
  UobBuilding(
    name: 'The Plug and The Tub',
    latitude: 51.37974,
    longitude: -2.32687,
    aliases: [
      'Plug and The Tub',
      'The Plug and The Tub',
      'plug and the tub',
      'the plug and the tub',
    ],
  ),
  UobBuilding(
    name: 'The Quads accommodation complex',
    latitude: 51.379633,
    longitude: -2.322714,
    aliases: [
      'Quads accommodation complex',
      'The Quads accommodation complex',
      'quads accommodation complex',
      'the quads accommodation complex',
    ],
  ),
  UobBuilding(
    name: 'University Hall',
    latitude: 51.379248,
    longitude: -2.328883,
    aliases: [
      '2W',
      '2W UN HALL',
      '2W UN. HALL',
      '2W UNH',
      'UN Hall',
      'UN. Hall',
      'UNH',
      'University Hall',
      'un hall',
      'un. hall',
      'unh',
      'university hall',
    ],
  ),
  UobBuilding(
    name: 'University of Bath, Claverton Down campus',
    latitude: 51.378344,
    longitude: -2.325202,
    aliases: [
      'University of Bath, Claverton Down campus',
      'university of bath  claverton down campus',
      'university of bath claverton down campus',
      'university of bath, claverton down campus',
    ],
  ),
  UobBuilding(
    name: 'Welfare room',
    latitude: 51.379856,
    longitude: -2.330045,
    aliases: ['Welfare room', 'welfare room'],
  ),
  UobBuilding(
    name: 'West Accommodation Centre',
    latitude: 51.38037,
    longitude: -2.33227,
    aliases: ['West Accommodation Centre', 'west accommodation centre'],
  ),
  UobBuilding(
    name: 'West Car Park',
    latitude: 51.37972,
    longitude: -2.3329,
    aliases: ['West Car Park', 'west car park'],
  ),
  UobBuilding(
    name: 'Westwood accommodation complex',
    latitude: 51.38104,
    longitude: -2.32957,
    aliases: [
      'Westwood accommodation complex',
      'westwood accommodation complex',
    ],
  ),
  UobBuilding(
    name: 'Woodland Court accommodation complex',
    latitude: 51.3807012,
    longitude: -2.3249274,
    aliases: [
      'Woodland Court accommodation complex',
      'woodland court accommodation complex',
    ],
  ),
];
